####################################################################
# PopulationSim Properties
####################################################################

# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: true
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: false
GROUP_BY_INCIDENCE_SIGNATURE: true
USE_SIMUL_INTEGERIZER: true
USE_CVXPY: false
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, TRACT]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography: # Not utilized - Andrew
  TAZ: 100
  TRACT: 10200


# Data Directory
# ------------------------------------------------------------------
data_dir: data



# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
- tablename: households
  filename: seed_households_06_115_2020.csv # name will be changed each iteration
  index_col: hh_id
  rename_columns:
    SERIALNO: hh_id
      # hhnum: hh_id
- tablename: persons
    # expression_filename: seed_persons_expressions.csv
  filename: seed_persons_06_115_2020.csv # name will be changed each iteration
  rename_columns:
    SERIALNO: hh_id
      # hhnum: hh_id
    SPORDER: per_num
    # drop unused mixed type fields to avoid PyTables pipeline performance issues
    # (PyTables will pickle object types that it cannot map directly to c-types)
- tablename: geo_cross_walk
  filename: geo_cross_walk_06_115_2020.csv # name will be changed each iteration
  column_map:
    TRACTCE: TRACT
- tablename: TRACT_control_data
  filename: control_totals_tract_06_115_2020.csv # name will be changed each iteration
  # - tablename: REGION_control_data
    #filename : control_totals_meta.csv
    # filename : scaled_control_totals_meta.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
  - summary_TRACT
  # - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households_06_115_2020.csv # name will be changed each iteration
    columns: # The columns you want outputted in the synthetic households
    - NOC
    - NP
    - HINCP
    - TEN
    - HEAD_RACE
    - NUM_ADULTS
    - NUM_WORKERS
    - ADJINC
  persons:
    filename: synthetic_persons_06_115_2020.csv # name will be chaned each iteration
    columns: # The columns you want outputted in the synthetic persons
    - AGEP
    - RAC1P
    - SEX
    - RELSHIPP
    - ESR
    - PINCP
    - ADJINC



# Model steps for base mode
# ------------------------------------------------------------------
models:
- input_pre_processor
- setup_data_structures
- initial_seed_balancing
- meta_control_factoring
- final_seed_balancing
- integerize_final_seed_weights
- sub_balancing.geography=TRACT
- expand_households
# - write_data_dictionary
# I feel like we don't need the summarize step
# - summarize 
- write_tables
- write_synthetic_population

# I don't think this is really utilized - Andrew
resume_after:
